#!/usr/bin/env python3
"""Contrast gate for neutral.tokens.json.

Resolves every semantic color token to hex in the light and dark modes, then
checks WCAG 2.x contrast for each text-on-surface / UI pair. Writes
contrast-report.md and exits non-zero if any required pair fails, so the tokens
cannot drive Figma variables until the palette is legible in both modes.

Generic and dependency-free (stdlib only). Re-run after any semantic edit.
"""
import json, sys, pathlib

HERE = pathlib.Path(__file__).parent
TOKENS = HERE / "neutral.tokens.json"
REPORT = HERE / "contrast-report.md"


def load():
    return json.loads(TOKENS.read_text())


def hexval(ref, prim):
    """Resolve a '{primitive.x.y}' reference (or a literal hex) to #rrggbb."""
    if ref.startswith("{") and ref.endswith("}"):
        parts = ref[1:-1].split(".")
        node = {"primitive": prim}
        for p in parts:
            node = node[p]
        return node["$value"]
    return ref


def rel_lum(hexstr):
    h = hexstr.lstrip("#")
    r, g, b = (int(h[i:i + 2], 16) / 255 for i in (0, 2, 4))
    def lin(c):
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = lin(r), lin(g), lin(b)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b


def ratio(fg, bg):
    a, b = rel_lum(fg), rel_lum(bg)
    hi, lo = max(a, b), min(a, b)
    return (hi + 0.05) / (lo + 0.05)


# (foreground role, background role, min ratio, gated, what it is)
# gated=False rows are decorative (WCAG 1.4.11 exempt); reported for information,
# never a build blocker. Decorative dividers do not carry a contrast requirement.
PAIRS = [
    ("text", "bg", 4.5, True, "body text on page"),
    ("text", "surface", 4.5, True, "body text on card"),
    ("text", "surface-raised", 4.5, True, "body text on raised card"),
    ("text-muted", "bg", 4.5, True, "muted text on page"),
    ("text-muted", "surface", 4.5, True, "muted text on card"),
    ("on-accent", "accent", 4.5, True, "button / chip label"),
    ("success", "surface", 4.5, True, "success text on card"),
    ("warning", "surface", 4.5, True, "warning text on card"),
    ("danger", "surface", 4.5, True, "danger text on card"),
    ("accent", "bg", 4.5, True, "accent link text on page"),
    ("accent", "surface", 4.5, True, "accent link text on card"),
    ("text-subtle", "surface", 3.0, True, "subtle meta, LARGE/UI only (>=18px)"),
    ("border-interactive", "surface", 3.0, True, "unfocused control boundary (UI)"),
    ("border-interactive", "bg", 3.0, True, "unfocused control boundary on page (UI)"),
    ("focus", "bg", 3.0, True, "focus ring on page (UI)"),
    ("focus", "surface", 3.0, True, "focus ring on card (UI)"),
    ("border", "surface", 3.0, False, "decorative divider (1.4.11 exempt, info)"),
    ("border-strong", "surface", 3.0, False, "decorative emphasis divider (1.4.11 exempt, info)"),
]


def main():
    data = load()
    prim = data["primitive"]
    sem = data["semantic"]["color"]

    def resolved(role, mode):
        node = sem[role]
        ref = node["$extensions"]["mode"][mode]
        return hexval(ref, prim)

    # Convention gate: $value must equal the light-mode value for every role
    # (the file documents "$value is the light mode"). A plain DTCG consumer
    # reads $value, so any drift ships a colour the contrast pass never tested.
    drift = []
    for role, node in sem.items():
        v = hexval(node["$value"], prim)
        lightv = hexval(node["$extensions"]["mode"]["light"], prim)
        if v != lightv:
            drift.append(f"{role}: $value {v} != mode.light {lightv}")

    rows, failures, gated_total = [], 0, 0
    for mode in ("light", "dark"):
        for fg, bg, minr, gated, label in PAIRS:
            fgx, bgx = resolved(fg, mode), resolved(bg, mode)
            r = ratio(fgx, bgx)
            ok = r >= minr
            if gated:
                gated_total += 1
                if not ok:
                    failures += 1
            status = ("PASS" if ok else "FAIL") if gated else "INFO"
            rows.append((mode, f"{fg} on {bg}", label, fgx, bgx, r, minr, status))

    cell = {"PASS": "PASS", "FAIL": "**FAIL**", "INFO": "info (decorative)"}
    lines = ["# Contrast report: neutral.tokens.json",
             "",
             "WCAG 2.x contrast for every semantic text/UI pair, both modes. "
             "Generated by `check-contrast.py`; do not edit by hand. `info` rows "
             "are decorative (WCAG 1.4.11 exempt): reported, never gated.",
             "",
             "| Mode | Pair | Role | fg | bg | Ratio | Min | Result |",
             "|---|---|---|---|---|---|---|---|"]
    for mode, pair, label, fgx, bgx, r, minr, status in rows:
        lines.append(f"| {mode} | {pair} | {label} | `{fgx}` | `{bgx}` | "
                     f"{r:.2f}:1 | {minr}:1 | {cell[status]} |")
    lines += ["",
              f"**Gated result: {gated_total - failures}/{gated_total} pass"
              f"{'' if failures == 0 else f', {failures} FAIL'}.** "
              "Decorative (info) rows are not gated.",
              "",
              "Convention ($value == mode.light for every role): "
              f"{'OK' if not drift else 'DRIFT: ' + '; '.join(drift)}.",
              ""]
    REPORT.write_text("\n".join(lines))

    print("\n".join(f"[{status:4}] {mode:5} {pair:30} {r:5.2f}:1 (min {minr})"
                    for mode, pair, label, fgx, bgx, r, minr, status in rows))
    if drift:
        print("\nCONVENTION DRIFT ($value must equal mode.light):")
        for d in drift:
            print("  " + d)
    else:
        print("\nConvention: $value == mode.light for all roles (OK).")
    print(f"Gated: {gated_total - failures}/{gated_total} pass; "
          f"report -> {REPORT.name}")
    return 1 if (failures or drift) else 0


if __name__ == "__main__":
    sys.exit(main())
