#!/usr/bin/env python3
"""Emit build-variables.js from ../tokens/neutral.tokens.json.

The token file is the single source for the variable collections. This script
inlines its values into a generic design-tool script (Figma Plugin API, run via
use_figma with the figma-use skill loaded first) that creates or updates two
collections: Primitives (one mode, "Value") and Semantic (modes "Light" and
"Dark", every value an alias to a primitive). Variables are addressed by NAME;
nothing here carries a node or variable id, so the script runs in any file.

Usage:
  python3 emit-variables-script.py            # writes build-variables.js beside this file
  python3 emit-variables-script.py --check    # exit 1 if build-variables.js is stale

Scope policy (which property pickers a semantic role appears in) is recorded
here because the DTCG file has no field for it; it mirrors the reference
template. Primitive colors carry no scope on purpose: consumers alias through
the semantic layer, and an unscoped primitive stays out of every picker.
"""
import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
TOKENS = os.path.join(HERE, "..", "tokens", "neutral.tokens.json")
OUT = os.path.join(HERE, "build-variables.js")

SCOPES = {
    "bg": ["FRAME_FILL"],
    "surface": ["FRAME_FILL", "SHAPE_FILL"],
    "surface-raised": ["FRAME_FILL", "SHAPE_FILL"],
    "text": ["TEXT_FILL"], "text-muted": ["TEXT_FILL"], "text-subtle": ["TEXT_FILL"],
    "border": ["STROKE_COLOR"], "border-strong": ["STROKE_COLOR"], "border-interactive": ["STROKE_COLOR"],
    "accent": ["FRAME_FILL", "SHAPE_FILL", "TEXT_FILL", "STROKE_COLOR"],
    "accent-hover": ["FRAME_FILL", "SHAPE_FILL"],
    "on-accent": ["FRAME_FILL", "TEXT_FILL"],
    "focus": ["STROKE_COLOR"],
    "success": ["FRAME_FILL", "TEXT_FILL", "STROKE_COLOR"],
    "warning": ["FRAME_FILL", "TEXT_FILL", "STROKE_COLOR"],
    "danger": ["FRAME_FILL", "TEXT_FILL", "STROKE_COLOR"],
}
DEFAULT_SCOPES = ["FRAME_FILL", "SHAPE_FILL", "TEXT_FILL", "STROKE_COLOR"]


def ref_to_name(ref):
    """'{primitive.gray.50}' -> 'gray/50'; '{primitive.white}' -> 'white'."""
    m = re.match(r"^\{primitive\.(.+)\}$", ref.strip())
    if not m:
        raise ValueError("semantic value must alias a primitive: " + ref)
    return m.group(1).replace(".", "/")


def px(val):
    s = str(val).strip()
    return float(s[:-2]) if s.endswith("px") else float(s)


def collect(tokens):
    prims, sems = [], []
    for group, ramp in tokens["primitive"].items():
        if isinstance(ramp, dict) and "$value" in ramp:
            prims.append({"name": group, "type": "COLOR", "value": ramp["$value"], "scopes": []})
        else:
            for step, tok in ramp.items():
                if step.startswith("$"):
                    continue
                prims.append({"name": group + "/" + step, "type": "COLOR", "value": tok["$value"], "scopes": []})
    for step, tok in tokens["space"].items():
        if not step.startswith("$"):
            prims.append({"name": "space/" + step, "type": "FLOAT", "value": px(tok["$value"]), "scopes": ["WIDTH_HEIGHT", "GAP"]})
    for step, tok in tokens["radius"].items():
        if not step.startswith("$"):
            prims.append({"name": "radius/" + step, "type": "FLOAT", "value": px(tok["$value"]), "scopes": ["CORNER_RADIUS"]})
    for role, tok in tokens["semantic"]["color"].items():
        if role.startswith("$"):
            continue
        modes = tok["$extensions"]["mode"]
        sems.append({"name": "color/" + role, "light": ref_to_name(modes["light"]), "dark": ref_to_name(modes["dark"]),
                     "scopes": SCOPES.get(role, DEFAULT_SCOPES), "code": {"WEB": "--color-" + role},
                     "description": tok.get("$description", "")})
    return prims, sems


TEMPLATE = r'''// build-variables.js — GENERATED by emit-variables-script.py from ../tokens/neutral.tokens.json.
// Do not edit by hand; edit the token file and re-run the emitter.
//
// Run inside the design tool's script runner (use_figma, figma-use skill loaded first) on the
// target file. Creates or updates the Primitives collection (one mode, "Value") and the Semantic
// collection ("Light" + "Dark", every value an alias to a primitive). Idempotent: re-running
// updates values in place and never duplicates a variable. Needs a plan that allows two modes.
// Nothing here carries a file, node, or variable id; every variable is addressed by name.

const PRIMITIVES = %(prims)s;
const SEMANTIC = %(sems)s;

const hexToRgb = (h) => { const n = parseInt(h.replace('#', '').slice(0, 6), 16); return { r: ((n >> 16) & 255) / 255, g: ((n >> 8) & 255) / 255, b: (n & 255) / 255 }; };
const collections = await figma.variables.getLocalVariableCollectionsAsync();
const existing = {};
for (const v of await figma.variables.getLocalVariablesAsync()) existing[v.variableCollectionId + '|' + v.name] = v;
const created = [], updated = [];

let prim = collections.find((c) => c.name === 'Primitives') || figma.variables.createVariableCollection('Primitives');
if (prim.modes[0].name !== 'Value') prim.renameMode(prim.modes[0].modeId, 'Value');
const valueMode = prim.modes[0].modeId;
for (const p of PRIMITIVES) {
  let v = existing[prim.id + '|' + p.name];
  if (!v) { v = figma.variables.createVariable(p.name, prim, p.type); created.push(p.name); } else updated.push(p.name);
  v.scopes = p.scopes;
  v.setValueForMode(valueMode, p.type === 'COLOR' ? hexToRgb(p.value) : p.value);
  existing[prim.id + '|' + p.name] = v;
}

let sem = collections.find((c) => c.name === 'Semantic') || figma.variables.createVariableCollection('Semantic');
// Modes are looked up by name first; the default mode is renamed only when neither name exists yet,
// so a collection that already has Light and Dark (in any order) is left as it is.
let lightEntry = sem.modes.find((m) => m.name === 'Light');
let darkEntry = sem.modes.find((m) => m.name === 'Dark');
if (!lightEntry && !darkEntry) { sem.renameMode(sem.modes[0].modeId, 'Light'); lightEntry = sem.modes.find((m) => m.name === 'Light'); }
if (!lightEntry) throw new Error('Semantic collection has a Dark mode but no Light mode; rename its default mode to Light and re-run');
const lightMode = lightEntry.modeId;
const darkMode = darkEntry ? darkEntry.modeId : sem.addMode('Dark');
for (const s of SEMANTIC) {
  let v = existing[sem.id + '|' + s.name];
  if (!v) { v = figma.variables.createVariable(s.name, sem, 'COLOR'); created.push(s.name); } else updated.push(s.name);
  v.scopes = s.scopes;
  v.setVariableCodeSyntax('WEB', s.code.WEB);
  if (s.description) v.description = s.description;
  const L = existing[prim.id + '|' + s.light], D = existing[prim.id + '|' + s.dark];
  if (!L || !D) throw new Error('primitive missing for ' + s.name + ': ' + s.light + ' / ' + s.dark);
  v.setValueForMode(lightMode, figma.variables.createVariableAlias(L));
  v.setValueForMode(darkMode, figma.variables.createVariableAlias(D));
}
return {
  primitives: prim.variableIds.length, semantic: sem.variableIds.length,
  created: created.length, updated: updated.length,
  collections: { Primitives: prim.id, Semantic: sem.id }, modes: { Light: lightMode, Dark: darkMode },
};
'''


def render(tokens):
    prims, sems = collect(tokens)
    return TEMPLATE % {"prims": json.dumps(prims, ensure_ascii=False, indent=1),
                       "sems": json.dumps(sems, ensure_ascii=False, indent=1)}


def main(argv):
    tokens = json.load(open(TOKENS, encoding="utf-8"))
    text = render(tokens)
    if "--check" in argv:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print("build-variables.js is stale: run emit-variables-script.py")
            return 1
        print("build-variables.js is current")
        return 0
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(text)
    prims, sems = collect(tokens)
    print("wrote build-variables.js: %d primitives, %d semantic roles" % (len(prims), len(sems)))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
